AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

Globals:
  Function:
    Timeout: 20
    MemorySize: 512
    Environment:
      Variables:
        DB_URL: "jdbc:postgresql://dpg-crppk7jv2p9s7389nrhg-a.oregon-postgres.render.com/mailsender_dox0"
        DB_USERNAME: "mailsender_dox0_user"
        DB_PASSWORD: "iiDOG6vsQKsOBcwSc0FxIuFXkMfDq9oh"

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: HelloWorldFunction
      Handler: helloworld.App::handleRequest
      Runtime: java17
      Architectures:
        - x86_64
      Environment:
        Variables:
          PARAM1: VALUE
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hi
            Method: get
        Create1Person:
          Type: Api
          Properties:
            Path: /person
            Method: post
        ShowAllPersons:
          Type: Api
          Properties:
            Path: /showAllPersons
            Method: get
        UpdatePerson:
          Type: Api
          Properties:
            Path: /person/{person_id}
            Method: put
        Delete1Persons:
          Type: Api
          Properties:
            Path: /person/{person_id}
            Method: delete

Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
